include ../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../Bin

INC_DIRS = \
	../../Include \
	../Common

SRC_FILES = *.cpp

USED_LIBS += OpenNI2

EXE_NAME = MultipleStreamRead

CFLAGS += -Wall -Wno-unused-local-typedefs

include ../../ThirdParty/PSCommon/BuildSystem/CommonCppMakefile
